# 详细配置请参考: https://karin.fun/config/friend

# 全局默认配置
default:
  # 好友消息冷却时间，单位秒,0则无限制
  cd: 0
  # 机器人响应模式(私聊没有群聊那么多模式)，0-所有 2-仅回应管理员 3-仅回应别名 5-管理员无限制，非管理员别名 6-仅回应主人
  mode: 0
  # 机器人别名 设置后别名+指令触发机器人
  alias:
    - k
  # 白名单插件、功能，只有在白名单中的插件、功能才会响应 `karin-plugin-test:app.js` `karin-plugin-test:测试转发`
  enable: []
  # 黑名单插件、功能，黑名单中的插件、功能不会响应 `karin-plugin-test:app.js` `karin-plugin-test:测试转发`
  disable: []

# 单个Bot默认配置
Bot:selfId:
  cd: 0
  mode: 0
  alias: []
  enable: []
  disable: []

# 单个Bot:单个好友、频道成员 配置
Bot:selfId:userId:
  cd: 0
  mode: 0
  alias: []
  enable: []
  disable: []
