# 日志最多显示1000行
lines: 1000

apps:
  - name: karin
    # 入口文件
    script: index.js
    # 自动重启
    autorestart: true
    # 重启次数
    max_restarts: 60
    # 最大内存限制
    max_memory_restart: 1G
    # 重启延迟
    restart_delay: 2000
    # 合并日志
    merge_logs: true
    # 错误日志
    error_file: ./logs/pm2_error.log
    # 输出日志
    out_file: ./logs/pm2_out.log
