# 这里的所有配置会全部传递给redis 详情参数请查阅

# url的优先级是高于下方配置的，如果url没有的参数会读取最下方配置
# redis[s]://[[username][:password]@][host][:port][/db-number]
url: redis://127.0.0.1:6379

# 套接字连接属性
socket:
  # 地址
  host: 127.0.0.1
  # 端口
  port: 6379

# 用户名
username:
# 密码
password:
# 数据库索引
database: 0
