# redis地址
host: 127.0.0.1
# redis端口
port: 6379
# redis用户名，可以为空
username:
# redis密码，没有密码可以为空
password:
# redis数据库
db: 0

# 集群配置
cluster:
  # 是否启用集群
  enable: false
  # 集群地址
  rootNodes:
    - url: Redis://127.0.0.1:6379/0
