# 当前文件热更新是否重启http服务
hmrToServer: false

# 鉴权秘钥
authKey: ""

# http监听地址
host: 0.0.0.0

# http端口
port: 7000

# ws api请求超时时间 秒
timeout: 60

# onebot http
onebotHttp:
  - selfId: default
    api: http://127.0.0.1:7777
    # 强烈建议配置 防止恶意伪造事件上报
    token: ""

# 反向ws鉴权秘钥
reverseWsToken: ""
# onebot11 正向WebSocket地址
forwardWs: []

# websocket 渲染器地址 ws://127.0.0.1:7005/ws/render
renderWs: []
# http渲染器地址
renderHttp: []

# console控制台适配器api配置
console:
  # 只允许本地访问
  isLocal: true
  # 如果 isLocal 为 false 则需要配置 token
  token: ""
  # 自定义host
  host:

# http根路由随机返回的文案
rootMsg:
  - 雪霁银妆素，桔高映琼枝。
  - 若知是梦何须醒，不比真如一相会。
  - 一片春愁待酒浇，江上舟摇，楼上帘招。
  - 人生自是有情痴，此恨不关风与月。
