packages:
  - packages/*
  - "!packages/karin-plugin-ts"
  - "!packages/karin-plugin-js"
onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@karinjs/node-pty"
  - "@karinjs/sqlite3-cjs"
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

catalog:
  axios: "npm:@karinjs/axios"
  express: "npm:@karinjs/express"
  lodash: "npm:@karinjs/lodash"
  ws: "npm:@karinjs/ws"
  moment: "npm:@karinjs/moment"
  redis: "npm:@karinjs/redis"
  sqlite3: "npm:@karinjs/sqlite3-cjs"
  art-template: "npm:@karinjs/art-template"
  node-schedule: "npm:@karinjs/node-schedule"
  jsonwebtoken: "npm:@karinjs/jsonwebtoken"
  log4js: 6.9.1
  chalk: 5.4.1
  chokidar: 4.0.3
  yaml: 2.7.0
