packages:
  - packages/*
  - "!packages/karin-plugin-ts"
  - "!packages/karin-plugin-js"
onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@karinjs/node-pty"
  - "@karinjs/sqlite3-cjs"
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
