/** npm 排除列表 */
export const NPM_EXCLUDE_LIST = [
  '@karinjs/node-pty',
  '@karinjs/plugin-webui-network-monitor',
  '@karinjs/plugins-list',
  '@types/express',
  '@types/lodash',
  '@types/node-schedule',
  '@types/ws',
  'art-template',
  'axios',
  'chalk',
  'chokidar',
  'commander',
  'dotenv',
  'express',
  'level',
  'lodash',
  'log4js',
  'moment',
  'node-schedule',
  'redis',
  'ws',
  'yaml',
  'sqlite3',
]
