/**
 * OneBot11公开Api
 */
export const enum OB11Api {
  sendPrivateMsg = 'send_private_msg',
  sendGroupMsg = 'send_group_msg',
  sendMsg = 'send_msg',
  deleteMsg = 'delete_msg',
  getMsg = 'get_msg',
  getForwardMsg = 'get_forward_msg',
  sendLike = 'send_like',
  setGroupKick = 'set_group_kick',
  setGroupBan = 'set_group_ban',
  setGroupAnonymousBan = 'set_group_anonymous_ban',
  setGroupWholeBan = 'set_group_whole_ban',
  setGroupAdmin = 'set_group_admin',
  setGroupAnonymous = 'set_group_anonymous',
  setGroupCard = 'set_group_card',
  setGroupName = 'set_group_name',
  setGroupLeave = 'set_group_leave',
  setGroupSpecialTitle = 'set_group_special_title',
  setFriendAddRequest = 'set_friend_add_request',
  setGroupAddRequest = 'set_group_add_request',
  getLoginInfo = 'get_login_info',
  getStrangerInfo = 'get_stranger_info',
  getFriendList = 'get_friend_list',
  getGroupInfo = 'get_group_info',
  getGroupList = 'get_group_list',
  getGroupMemberInfo = 'get_group_member_info',
  getGroupMemberList = 'get_group_member_list',
  getGroupHonorInfo = 'get_group_honor_info',
  getCookies = 'get_cookies',
  getCsrfToken = 'get_csrf_token',
  getCredentials = 'get_credentials',
  getRecord = 'get_record',
  getImage = 'get_image',
  canSendImage = 'can_send_image',
  canSendRecord = 'can_send_record',
  getStatus = 'get_status',
  getVersionInfo = 'get_version_info',
  setRestart = 'set_restart',
  cleanCache = 'clean_cache',
  getVersion = 'get_version',
  sendForwardMsg = 'send_forward_msg',
  getFriendMsgHistory = 'get_friend_msg_history',
  getGroupMsgHistory = 'get_group_msg_history',
  setMsgEmojiLike = 'set_msg_emoji_like',
  uploadGroupFile = 'upload_group_file',
  uploadPrivateFile = 'upload_private_file',
  getEssenceMsgList = 'get_essence_msg_list',
  setEssenceMsg = 'set_essence_msg',
  deleteEssenceMsg = 'delete_essence_msg',
}
