/** @type {Partial<import("typedoc").TypeDocOptions>} */
const config = {
  $schema: 'https://typedoc.org/schema.json',
  entryPoints: [
    'src/index.ts',
  ],
  docsRoot: './',
  out: './guide/api/types',
  theme: 'default',
  name: 'Karin API Docs',
  readme: '../../README.md',
  lang: 'zh',
  exclude: [
    '**/*.test.ts',
    '**/*.spec.ts',
    '**/node_modules/**',
  ],
  excludePrivate: false,
  excludeProtected: false,
  excludeInternal: true,
  hideGenerator: true,
  kindSortOrder: [
    'Document',
    'Project',
    'Module',
    'Namespace',
    'Enum',
    'EnumMember',
    'Class',
    'Interface',
    'TypeAlias',
    'Constructor',
    'Property',
    'Variable',
    'Function',
    'Accessor',
    'Method',
    'Parameter',
    'TypeParameter',
    'TypeLiteral',
    'CallSignature',
    'ConstructorSignature',
    'IndexSignature',
    'GetSignature',
    'SetSignature',
  ],
  categorizeByGroup: true,
  defaultCategory: '其他',
  categoryOrder: [
    '主要功能',
    '工具函数',
    '类型定义',
    '接口',
    '枚举',
    '其他',
  ],
  gitRevision: 'main',
  gitRemote: 'origin',
  includeVersion: true,
  searchInComments: true,
  searchInDocuments: true,
  treatWarningsAsErrors: false,
  logLevel: 'Error',
  skipErrorChecking: true,
  blockTags: [
    '@description',
    '@version',
  ],
  plugin: [
    'typedoc-plugin-markdown',
    'typedoc-vitepress-theme',
  ],
}

export default config
