name: 应用配置
view:
  - key: 黑名单
    comment: 黑名单相关
    path: "BlackList"
    type: "group"
    part:
      - key: 黑名单用户
        path: "BlackList.users"
        type: "boolean"
      - key: 黑名单群聊
        path: "BlackList.groups"
        type: "boolean"
      - key: 消息日志黑名单群聊
        comment: 设置后不会打印该群的消息日志
        path: "BlackList.GroupMsgLog"
        type: "boolean"
  - key: 白名单
    comment: 白名单相关
    path: "WhiteList"
    type: "group"
    part:
      - key: 白名单用户
        path: "WhiteList.users"
        type: "boolean"
      - key: 白名单群聊
        path: "WhiteList.groups"
        type: "boolean"
      - key: 消息日志白名单群聊
        comment: 消息日志白名单群聊 设置后只会打印该群的消息日志
        path: "WhiteList.GroupMsgLog"
        type: "boolean"
  - key: 群聊
    path: "GroupConfig"
    type: "group"
    part:
      - key: 消息冷却时间
        comment: 群聊中所有消息冷却时间
        path: "GroupConfig.GroupCD"
        type: "boolean"
      - key: 个人消息冷却时间
        comment: 群聊中 每个人的消息冷却时间
        path: "GroupConfig.GroupUserCD"
        type: "boolean"
      - key: 机器人响应模式
        path: "GroupConfig.mode"
        type: "boolean"
      - key: 机器人前缀
        comment: 机器人前缀 设置后前缀+指令触发机器人
        path: "GroupConfig.alias"
        type: "boolean"
      - key: 白名单插件、功能
        comment: 白名单插件、功能，只有在白名单中的插件、功能才会响应
        path: "GroupConfig.enable"
        type: "boolean"
      - key: 黑名单插件、功能
        comment: 黑名单插件、功能，黑名单中的插件、功能不会响应
        path: "GroupConfig.disable"
        type: "boolean"
  - key: 私聊
    path: "PrivateConfig"
    type: "group"
    part:
      - key: 是否开启私聊
        comment: 是否开启私聊
        path: "PrivateConfig.enable"
        type: "boolean"
