/**
 * @fileoverview Schema-Driven UI 类型定义
 * @description 重新导出 @karinjs/schema-types 包的所有类型
 *
 * 此文件作为本地类型的入口点，所有类型定义已迁移到独立的 @karinjs/schema-types 包中，
 * 以便前后端共享使用。
 */

// 从共享包重新导出所有类型
export type {
  // 基础类型
  I18nKey,
  I18nString,
  IconName,
  ConditionOperator,
  SimpleCondition,
  AndCondition,
  OrCondition,
  NotCondition,
  ConditionExpression,
  ValidationType,
  ValidationRule,
  ColumnSpan,
  FieldLayout,
  SelectItem,
  TableColumnFormat,
  TableColumn,
  ComponentColor,
  ForegroundColor,
  ComponentSize,
  ExtendedSize,
  ModalSize,
  RadiusType,
  ComponentVariant,
  InputVariant,
  AccordionVariant,
  TabsVariant,
  ChipVariant,
  UnderlineType,

  // 字段基础
  FieldSchemaBase,

  // 基础输入字段
  TextFieldOptions,
  TextFieldSchema,
  PasswordFieldOptions,
  PasswordFieldSchema,
  NumberFieldOptions,
  NumberFieldSchema,
  TextareaFieldOptions,
  TextareaFieldSchema,
  SwitchFieldOptions,
  SwitchFieldSchema,
  SelectFieldOptions,
  SelectFieldSchema,

  // 高级输入字段
  CheckboxFieldOptions,
  CheckboxFieldSchema,
  CheckboxGroupFieldOptions,
  CheckboxGroupFieldSchema,
  RadioGroupFieldOptions,
  RadioGroupFieldSchema,
  AutocompleteFieldOptions,
  AutocompleteFieldSchema,
  SliderMark,
  SliderFieldOptions,
  SliderFieldSchema,
  DatePickerFieldOptions,
  DatePickerFieldSchema,
  DateRangePickerFieldOptions,
  DateRangePickerFieldSchema,
  TimeInputFieldOptions,
  TimeInputFieldSchema,
  ColorPickerFieldOptions,
  ColorPickerFieldSchema,
  ImageUploadFieldOptions,
  ImageUploadFieldSchema,
  FileUploadFieldOptions,
  FileUploadFieldSchema,
  TagsInputFieldOptions,
  TagsInputFieldSchema,
  OtpInputFieldOptions,
  OtpInputFieldSchema,
  RatingFieldOptions,
  RatingFieldSchema,

  // 列表字段
  ListFieldOptions,
  ListFieldSchema,
  ObjectListEditModal,
  ObjectListFieldOptions,
  ObjectListFieldSchema,
  KeyValueFieldOptions,
  KeyValueFieldSchema,
  JsonEditorFieldOptions,
  JsonEditorFieldSchema,

  // 布局字段
  GroupFieldOptions,
  GroupFieldSchema,
  AccordionItem,
  AccordionFieldOptions,
  AccordionFieldSchema,
  TabItem,
  TabsFieldOptions,
  TabsFieldSchema,
  DividerFieldOptions,
  DividerFieldSchema,
  AlertVariant,
  AlertFieldOptions,
  AlertFieldSchema,
  SpacerFieldOptions,
  SpacerFieldSchema,
  ScrollAreaFieldOptions,
  ScrollAreaFieldSchema,

  // 展示字段
  ProgressFormatOptions,
  ProgressFieldOptions,
  ProgressFieldSchema,
  AvatarFieldOptions,
  AvatarFieldSchema,
  BadgePlacement,
  BadgeVariant,
  BadgeFieldOptions,
  BadgeFieldSchema,
  ChipFieldOptions,
  ChipFieldSchema,
  SnippetFieldOptions,
  SnippetFieldSchema,
  LinkFieldOptions,
  LinkFieldSchema,
  UserCardFieldOptions,
  UserCardFieldSchema,
  ImageFieldOptions,
  ImageFieldSchema,
  ButtonActionType,
  ButtonAction,
  ButtonFieldOptions,
  ButtonFieldSchema,
  SkeletonVariant,
  SkeletonFieldOptions,
  SkeletonFieldSchema,
  PaginationVariant,
  PaginationFieldOptions,
  PaginationFieldSchema,

  // 容器字段
  CardShadow,
  CardFieldOptions,
  CardFieldSchema,
  PopoverPlacement,
  TriggerVariant,
  PopoverTriggerFieldOptions,
  PopoverTriggerFieldSchema,
  TooltipColor,
  TooltipFieldOptions,
  TooltipFieldSchema,
  DrawerPlacement,
  DrawerTriggerFieldOptions,
  DrawerTriggerFieldSchema,
  ModalScrollBehavior,
  ModalTriggerFieldOptions,
  ModalTriggerFieldSchema,
  TableSelectionMode,
  TableFieldOptions,
  TableFieldSchema,
  ListboxSelectionMode,
  ListboxVariant,
  ListboxFieldOptions,
  ListboxFieldSchema,
  DropdownItem,
  DropdownSelectionMode,
  DropdownFieldOptions,
  DropdownFieldSchema,
  BreadcrumbItem,
  BreadcrumbsFieldOptions,
  BreadcrumbsFieldSchema,

  // 联合类型
  FieldSchema,
  FieldType,

  // 表单 Schema
  FormLayout,
  FormColumns,
  SubmitPosition,
  SubmitButtonConfig,
  FormOptions,
  SubmitMethod,
  DataTransform,
  SuccessAction,
  SubmitConfig,
  SchemaVersion,
  FormSchema,

  // 表单上下文
  FormValues,
  FormErrors,
  FormTouched,
  FormContextValue,
  FormSubmitHandler,
  FieldChangeHandler,
  ValidationResult,
  FormValidator,
} from '@karinjs/schema-types'
