name: Build Docker

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKERHUB_REPO: karinjs/karin
  GHCR_REPO: ghcr.io/karinjs/karin
  ALIYUN_REPO: registry.cn-hangzhou.aliyuncs.com/karinjs/karin

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}
            ${{ env.ALIYUN_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: 登陆 阿里云 镜像仓库
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.cn-hangzhou.aliyuncs.com
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}

      - uses: docker/build-push-action@v6
        id: build
        with:
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          file: packages/docker/Dockerfile
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}-amd64
            ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}-amd64
            ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }}-amd64
          push: true

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}
            ${{ env.ALIYUN_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: 登陆 阿里云 镜像仓库
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.cn-hangzhou.aliyuncs.com
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}

      - uses: docker/build-push-action@v6
        id: build
        with:
          platforms: linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          file: packages/docker/Dockerfile
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}-arm64
            ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}-arm64
            ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }}-arm64
          push: true

  create-manifest:
    runs-on: ubuntu-latest
    needs:
      - build-amd64
      - build-arm64
    steps:
      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: 登陆 阿里云 镜像仓库
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.cn-hangzhou.aliyuncs.com
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}
            ${{ env.ALIYUN_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: 创建并推送多平台清单
        run: |
          # 为DockerHub创建清单
          docker buildx imagetools create \
            -t ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }} \
            ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}-amd64 \
            ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}-arm64

          # 为GHCR创建清单
          docker buildx imagetools create \
            -t ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }} \
            ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}-amd64 \
            ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}-arm64

          # 为阿里云创建清单
          docker buildx imagetools create \
            -t ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }} \
            ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }}-amd64 \
            ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }}-arm64

      - name: 检查镜像
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}
          docker buildx imagetools inspect ${{ env.ALIYUN_REPO }}:${{ steps.meta.outputs.version }}
