name: Manual Publish Core
# 手动触发工作流
on:
  workflow_dispatch:
    inputs:
      version:
        description: "要发布的版本号 (例如: 1.0.0)"
        required: true
        type: string

# 设置权限
permissions:
  contents: write

jobs:
  publish-core:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 安装pnpm
      - name: 配置pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true

      # 构建项目
      - name: 构建项目
        run: pnpm build

      # 更新版本号
      - name: 更新版本号
        run: cd packages/core && pnpm pkg set version=${{ inputs.version }} && pnpm pkg delete peerDependencies

      # 发布到npm
      - name: 发布到NPM
        id: publish-to-npm
        uses: JS-DevTools/npm-publish@v3
        with:
          package: packages/core
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: 生成发布摘要
        run: |
          echo "## 发布信息 :" >> $GITHUB_STEP_SUMMARY
          echo "包名: \`${{ steps.publish-to-npm.outputs.name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "版本号: \`${{ steps.publish-to-npm.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
